# -*- coding: utf-8 -*-
# test
# Form implementation generated from reading ui file '.\certification.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1028, 556)
        Form.setMinimumSize(QtCore.QSize(1020, 0))
        self.funclte = QtWidgets.QPushButton(Form)
        self.funclte.setGeometry(QtCore.QRect(20, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funclte.setFont(font)
        self.funclte.setObjectName("funclte")
        self.funccamera = QtWidgets.QPushButton(Form)
        self.funccamera.setGeometry(QtCore.QRect(20, 188, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funccamera.setFont(font)
        self.funccamera.setAutoDefault(True)
        self.funccamera.setObjectName("funccamera")
        self.funcsiren = QtWidgets.QPushButton(Form)
        self.funcsiren.setGeometry(QtCore.QRect(20, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcsiren.setFont(font)
        self.funcsiren.setObjectName("funcsiren")
        self.funcbat = QtWidgets.QPushButton(Form)
        self.funcbat.setGeometry(QtCore.QRect(20, 290, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcbat.setFont(font)
        self.funcbat.setObjectName("funcbat")
        self.funcspk = QtWidgets.QPushButton(Form)
        self.funcspk.setGeometry(QtCore.QRect(20, 340, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcspk.setFont(font)
        self.funcspk.setObjectName("funcspk")
        self.funcvoicecall = QtWidgets.QPushButton(Form)
        self.funcvoicecall.setGeometry(QtCore.QRect(20, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcvoicecall.setFont(font)
        self.funcvoicecall.setObjectName("funcvoicecall")
        self.funcwireless = QtWidgets.QPushButton(Form)
        self.funcwireless.setGeometry(QtCore.QRect(20, 438, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless.setFont(font)
        self.funcwireless.setObjectName("funcwireless")
        self.funcio = QtWidgets.QPushButton(Form)
        self.funcio.setGeometry(QtCore.QRect(20, 488, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcio.setFont(font)
        self.funcio.setObjectName("funcio")
        self.rfmode = QtWidgets.QPushButton(Form)
        self.rfmode.setGeometry(QtCore.QRect(130, 80, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfmode.setFont(font)
        self.rfmode.setObjectName("rfmode")
        self.rfwifi = QtWidgets.QPushButton(Form)
        self.rfwifi.setGeometry(QtCore.QRect(130, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi.setFont(font)
        self.rfwifi.setObjectName("rfwifi")
        self.rfbt = QtWidgets.QPushButton(Form)
        self.rfbt.setGeometry(QtCore.QRect(130, 188, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt.setFont(font)
        self.rfbt.setObjectName("rfbt")
        self.rf900 = QtWidgets.QPushButton(Form)
        self.rf900.setGeometry(QtCore.QRect(130, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rf900.setFont(font)
        self.rf900.setObjectName("rf900")
        self.rfzwave = QtWidgets.QPushButton(Form)
        self.rfzwave.setGeometry(QtCore.QRect(130, 290, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave.setFont(font)
        self.rfzwave.setObjectName("rfzwave")
        self.rflte = QtWidgets.QPushButton(Form)
        self.rflte.setGeometry(QtCore.QRect(130, 340, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte.setFont(font)
        self.rflte.setObjectName("rflte")
        self.funcmode = QtWidgets.QPushButton(Form)
        self.funcmode.setGeometry(QtCore.QRect(20, 80, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcmode.setFont(font)
        self.funcmode.setObjectName("funcmode")
        self.funccamera_frame = QtWidgets.QFrame(Form)
        self.funccamera_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funccamera_frame.setFont(font)
        self.funccamera_frame.setAutoFillBackground(True)
        self.funccamera_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.funccamera_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.funccamera_frame.setObjectName("funccamera_frame")
        self.funccamera_on = QtWidgets.QPushButton(self.funccamera_frame)
        self.funccamera_on.setGeometry(QtCore.QRect(40, 90, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funccamera_on.setFont(font)
        self.funccamera_on.setObjectName("funccamera_on")
        self.label_2 = QtWidgets.QLabel(self.funccamera_frame)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.funccamera_off = QtWidgets.QPushButton(self.funccamera_frame)
        self.funccamera_off.setGeometry(QtCore.QRect(40, 130, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funccamera_off.setFont(font)
        self.funccamera_off.setObjectName("funccamera_off")
        self.funcsiren_frame = QtWidgets.QFrame(Form)
        self.funcsiren_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcsiren_frame.setFont(font)
        self.funcsiren_frame.setAutoFillBackground(True)
        self.funcsiren_frame.setObjectName("funcsiren_frame")
        self.funcsiren_on = QtWidgets.QPushButton(self.funcsiren_frame)
        self.funcsiren_on.setGeometry(QtCore.QRect(70, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcsiren_on.setFont(font)
        self.funcsiren_on.setObjectName("funcsiren_on")
        self.label_3 = QtWidgets.QLabel(self.funcsiren_frame)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.funcsiren_off = QtWidgets.QPushButton(self.funcsiren_frame)
        self.funcsiren_off.setGeometry(QtCore.QRect(70, 140, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcsiren_off.setFont(font)
        self.funcsiren_off.setObjectName("funcsiren_off")
        self.label_16 = QtWidgets.QLabel(self.funcsiren_frame)
        self.label_16.setGeometry(QtCore.QRect(0, 300, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.funcusb_detect = QtWidgets.QPushButton(self.funcsiren_frame)
        self.funcusb_detect.setGeometry(QtCore.QRect(70, 370, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcusb_detect.setFont(font)
        self.funcusb_detect.setObjectName("funcusb_detect")
        self.funcbat_frame = QtWidgets.QFrame(Form)
        self.funcbat_frame.setGeometry(QtCore.QRect(250, 10, 381, 511))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcbat_frame.setFont(font)
        self.funcbat_frame.setAutoFillBackground(True)
        self.funcbat_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.funcbat_frame.setObjectName("funcbat_frame")
        self.funcbat_on = QtWidgets.QPushButton(self.funcbat_frame)
        self.funcbat_on.setGeometry(QtCore.QRect(70, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcbat_on.setFont(font)
        self.funcbat_on.setObjectName("funcbat_on")
        self.label_4 = QtWidgets.QLabel(self.funcbat_frame)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.funcspk_frame = QtWidgets.QFrame(Form)
        self.funcspk_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcspk_frame.setFont(font)
        self.funcspk_frame.setAutoFillBackground(True)
        self.funcspk_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.funcspk_frame.setObjectName("funcspk_frame")
        self.funcspk_on = QtWidgets.QPushButton(self.funcspk_frame)
        self.funcspk_on.setGeometry(QtCore.QRect(80, 100, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcspk_on.setFont(font)
        self.funcspk_on.setObjectName("funcspk_on")
        self.label_5 = QtWidgets.QLabel(self.funcspk_frame)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.funcspk_off = QtWidgets.QPushButton(self.funcspk_frame)
        self.funcspk_off.setGeometry(QtCore.QRect(80, 140, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcspk_off.setFont(font)
        self.funcspk_off.setObjectName("funcspk_off")
        self.funcvalue = QtWidgets.QLineEdit(self.funcspk_frame)
        self.funcvalue.setGeometry(QtCore.QRect(160, 179, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcvalue.setFont(font)
        self.funcvalue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.funcvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.funcvalue.setObjectName("funcvalue")
        self.funccut = QtWidgets.QPushButton(self.funcspk_frame)
        self.funccut.setGeometry(QtCore.QRect(80, 180, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funccut.setFont(font)
        self.funccut.setObjectName("funccut")
        self.funcadd = QtWidgets.QPushButton(self.funcspk_frame)
        self.funcadd.setGeometry(QtCore.QRect(230, 180, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcadd.setFont(font)
        self.funcadd.setObjectName("funcadd")
        self.funcvoicecall_frame = QtWidgets.QFrame(Form)
        self.funcvoicecall_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcvoicecall_frame.setFont(font)
        self.funcvoicecall_frame.setAutoFillBackground(True)
        self.funcvoicecall_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.funcvoicecall_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.funcvoicecall_frame.setObjectName("funcvoicecall_frame")
        self.funcvoicecall_call = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.funcvoicecall_call.setGeometry(QtCore.QRect(70, 30, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcvoicecall_call.setFont(font)
        self.funcvoicecall_call.setObjectName("funcvoicecall_call")
        self.funcvoicecall_num = QtWidgets.QLineEdit(self.funcvoicecall_frame)
        self.funcvoicecall_num.setGeometry(QtCore.QRect(160, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcvoicecall_num.setFont(font)
        self.funcvoicecall_num.setText("")
        self.funcvoicecall_num.setObjectName("funcvoicecall_num")
        self.label_6 = QtWidgets.QLabel(self.funcvoicecall_frame)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.funcvoicecall_receive = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.funcvoicecall_receive.setGeometry(QtCore.QRect(70, 70, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcvoicecall_receive.setFont(font)
        self.funcvoicecall_receive.setObjectName("funcvoicecall_receive")
        self.funcvoicecall_hangup = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.funcvoicecall_hangup.setGeometry(QtCore.QRect(70, 110, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcvoicecall_hangup.setFont(font)
        self.funcvoicecall_hangup.setObjectName("funcvoicecall_hangup")
        self.readapn_btn = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.readapn_btn.setGeometry(QtCore.QRect(10, 150, 171, 31))
        self.readapn_btn.setObjectName("readapn_btn")
        self.readip_btn = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.readip_btn.setGeometry(QtCore.QRect(200, 150, 171, 31))
        self.readip_btn.setObjectName("readip_btn")
        self.readlte_btn = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.readlte_btn.setGeometry(QtCore.QRect(10, 190, 361, 31))
        self.readlte_btn.setObjectName("readlte_btn")
        self.ping_btn = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.ping_btn.setGeometry(QtCore.QRect(10, 270, 171, 31))
        self.ping_btn.setObjectName("ping_btn")
        self.setapn_btn = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.setapn_btn.setGeometry(QtCore.QRect(10, 430, 361, 31))
        self.setapn_btn.setObjectName("setapn_btn")
        self.setapn_edit = QtWidgets.QLineEdit(self.funcvoicecall_frame)
        self.setapn_edit.setGeometry(QtCore.QRect(10, 470, 361, 20))
        self.setapn_edit.setObjectName("setapn_edit")
        self.pinginter_edit = QtWidgets.QLineEdit(self.funcvoicecall_frame)
        self.pinginter_edit.setGeometry(QtCore.QRect(200, 350, 171, 31))
        self.pinginter_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.pinginter_edit.setObjectName("pinginter_edit")
        self.setautoapn_btn = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.setautoapn_btn.setGeometry(QtCore.QRect(10, 390, 361, 31))
        self.setautoapn_btn.setObjectName("setautoapn_btn")
        self.stopping_btn = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.stopping_btn.setGeometry(QtCore.QRect(200, 270, 171, 31))
        self.stopping_btn.setObjectName("stopping_btn")
        self.label_17 = QtWidgets.QLabel(self.funcvoicecall_frame)
        self.label_17.setGeometry(QtCore.QRect(10, 350, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.funcvoicecall_frame)
        self.label_18.setGeometry(QtCore.QRect(10, 320, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.web_edit = QtWidgets.QLineEdit(self.funcvoicecall_frame)
        self.web_edit.setGeometry(QtCore.QRect(200, 310, 171, 31))
        self.web_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.web_edit.setObjectName("web_edit")
        self.speedtest_btn = QtWidgets.QPushButton(self.funcvoicecall_frame)
        self.speedtest_btn.setGeometry(QtCore.QRect(10, 230, 361, 31))
        self.speedtest_btn.setObjectName("speedtest_btn")
        self.funcwireless_frame = QtWidgets.QFrame(Form)
        self.funcwireless_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_frame.setFont(font)
        self.funcwireless_frame.setAutoFillBackground(True)
        self.funcwireless_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.funcwireless_frame.setObjectName("funcwireless_frame")
        self.label_7 = QtWidgets.QLabel(self.funcwireless_frame)
        self.label_7.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.funcwireless_wifissid = QtWidgets.QLineEdit(self.funcwireless_frame)
        self.funcwireless_wifissid.setGeometry(QtCore.QRect(40, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_wifissid.setFont(font)
        self.funcwireless_wifissid.setText("")
        self.funcwireless_wifissid.setObjectName("funcwireless_wifissid")
        self.label_63 = QtWidgets.QLabel(self.funcwireless_frame)
        self.label_63.setGeometry(QtCore.QRect(40, 50, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.funcwireless_frame)
        self.label_64.setGeometry(QtCore.QRect(190, 70, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.funcwireless_frame)
        self.label_65.setGeometry(QtCore.QRect(190, 100, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.funcwireless_wifipsd = QtWidgets.QLineEdit(self.funcwireless_frame)
        self.funcwireless_wifipsd.setGeometry(QtCore.QRect(40, 100, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_wifipsd.setFont(font)
        self.funcwireless_wifipsd.setText("")
        self.funcwireless_wifipsd.setObjectName("funcwireless_wifipsd")
        self.funcwireless_wifion = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_wifion.setGeometry(QtCore.QRect(40, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_wifion.setFont(font)
        self.funcwireless_wifion.setObjectName("funcwireless_wifion")
        self.funcwireless_wifioff = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_wifioff.setGeometry(QtCore.QRect(160, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_wifioff.setFont(font)
        self.funcwireless_wifioff.setObjectName("funcwireless_wifioff")
        self.funcwireless_btscanon = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_btscanon.setGeometry(QtCore.QRect(40, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_btscanon.setFont(font)
        self.funcwireless_btscanon.setObjectName("funcwireless_btscanon")
        self.label_66 = QtWidgets.QLabel(self.funcwireless_frame)
        self.label_66.setGeometry(QtCore.QRect(40, 170, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.funcwireless_btoff = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_btoff.setGeometry(QtCore.QRect(160, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_btoff.setFont(font)
        self.funcwireless_btoff.setObjectName("funcwireless_btoff")
        self.funcwireless_btmac = QtWidgets.QLineEdit(self.funcwireless_frame)
        self.funcwireless_btmac.setGeometry(QtCore.QRect(40, 270, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_btmac.setFont(font)
        self.funcwireless_btmac.setObjectName("funcwireless_btmac")
        self.label_67 = QtWidgets.QLabel(self.funcwireless_frame)
        self.label_67.setGeometry(QtCore.QRect(190, 280, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.funcwireless_btscanoff = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_btscanoff.setGeometry(QtCore.QRect(160, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_btscanoff.setFont(font)
        self.funcwireless_btscanoff.setObjectName("funcwireless_btscanoff")
        self.funcwireless_btpair = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_btpair.setGeometry(QtCore.QRect(40, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_btpair.setFont(font)
        self.funcwireless_btpair.setObjectName("funcwireless_btpair")
        self.label_68 = QtWidgets.QLabel(self.funcwireless_frame)
        self.label_68.setGeometry(QtCore.QRect(40, 360, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.funcwireless_900off = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_900off.setGeometry(QtCore.QRect(160, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_900off.setFont(font)
        self.funcwireless_900off.setObjectName("funcwireless_900off")
        self.funcwireless_900on = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_900on.setGeometry(QtCore.QRect(40, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_900on.setFont(font)
        self.funcwireless_900on.setObjectName("funcwireless_900on")
        self.label_69 = QtWidgets.QLabel(self.funcwireless_frame)
        self.label_69.setGeometry(QtCore.QRect(40, 420, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.funcwireless_345on = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_345on.setGeometry(QtCore.QRect(40, 440, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_345on.setFont(font)
        self.funcwireless_345on.setObjectName("funcwireless_345on")
        self.funcwireless_enablebt = QtWidgets.QPushButton(self.funcwireless_frame)
        self.funcwireless_enablebt.setGeometry(QtCore.QRect(40, 190, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcwireless_enablebt.setFont(font)
        self.funcwireless_enablebt.setObjectName("funcwireless_enablebt")
        self.funcsensor_frame = QtWidgets.QFrame(Form)
        self.funcsensor_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcsensor_frame.setFont(font)
        self.funcsensor_frame.setAutoFillBackground(True)
        self.funcsensor_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.funcsensor_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.funcsensor_frame.setObjectName("funcsensor_frame")
        self.funcsensor_btn = QtWidgets.QPushButton(self.funcsensor_frame)
        self.funcsensor_btn.setGeometry(QtCore.QRect(60, 180, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcsensor_btn.setFont(font)
        self.funcsensor_btn.setObjectName("funcsensor_btn")
        self.funcsensor_edit = QtWidgets.QLineEdit(self.funcsensor_frame)
        self.funcsensor_edit.setGeometry(QtCore.QRect(150, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcsensor_edit.setFont(font)
        self.funcsensor_edit.setText("")
        self.funcsensor_edit.setObjectName("funcsensor_edit")
        self.label_8 = QtWidgets.QLabel(self.funcsensor_frame)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.rfwifi_frame = QtWidgets.QFrame(Form)
        self.rfwifi_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_frame.setFont(font)
        self.rfwifi_frame.setAutoFillBackground(True)
        self.rfwifi_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfwifi_frame.setObjectName("rfwifi_frame")
        self.label_9 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_9.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_11.setGeometry(QtCore.QRect(290, 60, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.rfwifi_region = QtWidgets.QLineEdit(self.rfwifi_frame)
        self.rfwifi_region.setGeometry(QtCore.QRect(20, 60, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_region.setFont(font)
        self.rfwifi_region.setAlignment(QtCore.Qt.AlignCenter)
        self.rfwifi_region.setObjectName("rfwifi_region")
        self.label_12 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_12.setGeometry(QtCore.QRect(290, 90, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_13.setGeometry(QtCore.QRect(290, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_14.setGeometry(QtCore.QRect(290, 150, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_15.setGeometry(QtCore.QRect(290, 180, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.rfwifi_band = QtWidgets.QLineEdit(self.rfwifi_frame)
        self.rfwifi_band.setGeometry(QtCore.QRect(20, 90, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_band.setFont(font)
        self.rfwifi_band.setAlignment(QtCore.Qt.AlignCenter)
        self.rfwifi_band.setObjectName("rfwifi_band")
        self.rfwifi_txbw = QtWidgets.QLineEdit(self.rfwifi_frame)
        self.rfwifi_txbw.setGeometry(QtCore.QRect(20, 120, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_txbw.setFont(font)
        self.rfwifi_txbw.setAlignment(QtCore.Qt.AlignCenter)
        self.rfwifi_txbw.setObjectName("rfwifi_txbw")
        self.rfwifi_mode = QtWidgets.QLineEdit(self.rfwifi_frame)
        self.rfwifi_mode.setGeometry(QtCore.QRect(20, 150, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_mode.setFont(font)
        self.rfwifi_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.rfwifi_mode.setObjectName("rfwifi_mode")
        self.rfwifi_channel = QtWidgets.QLineEdit(self.rfwifi_frame)
        self.rfwifi_channel.setGeometry(QtCore.QRect(20, 180, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_channel.setFont(font)
        self.rfwifi_channel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfwifi_channel.setObjectName("rfwifi_channel")
        self.rfwifi_modulationsend = QtWidgets.QPushButton(self.rfwifi_frame)
        self.rfwifi_modulationsend.setGeometry(QtCore.QRect(170, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_modulationsend.setFont(font)
        self.rfwifi_modulationsend.setObjectName("rfwifi_modulationsend")
        self.rfwifi_tonechannel = QtWidgets.QLineEdit(self.rfwifi_frame)
        self.rfwifi_tonechannel.setGeometry(QtCore.QRect(20, 310, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_tonechannel.setFont(font)
        self.rfwifi_tonechannel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfwifi_tonechannel.setObjectName("rfwifi_tonechannel")
        self.rfwifi_tonesend = QtWidgets.QPushButton(self.rfwifi_frame)
        self.rfwifi_tonesend.setGeometry(QtCore.QRect(170, 340, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_tonesend.setFont(font)
        self.rfwifi_tonesend.setObjectName("rfwifi_tonesend")
        self.label_23 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_23.setGeometry(QtCore.QRect(20, 250, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_24.setGeometry(QtCore.QRect(120, 310, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.rfwifi_tonefrequency = QtWidgets.QLineEdit(self.rfwifi_frame)
        self.rfwifi_tonefrequency.setGeometry(QtCore.QRect(20, 280, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_tonefrequency.setFont(font)
        self.rfwifi_tonefrequency.setAlignment(QtCore.Qt.AlignCenter)
        self.rfwifi_tonefrequency.setObjectName("rfwifi_tonefrequency")
        self.label_25 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_25.setGeometry(QtCore.QRect(120, 280, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_26.setGeometry(QtCore.QRect(220, 410, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.rfwifi_rxchannel = QtWidgets.QLineEdit(self.rfwifi_frame)
        self.rfwifi_rxchannel.setGeometry(QtCore.QRect(20, 410, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_rxchannel.setFont(font)
        self.rfwifi_rxchannel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfwifi_rxchannel.setObjectName("rfwifi_rxchannel")
        self.rfwifi_rxsend = QtWidgets.QPushButton(self.rfwifi_frame)
        self.rfwifi_rxsend.setGeometry(QtCore.QRect(170, 440, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_rxsend.setFont(font)
        self.rfwifi_rxsend.setObjectName("rfwifi_rxsend")
        self.label_28 = QtWidgets.QLabel(self.rfwifi_frame)
        self.label_28.setGeometry(QtCore.QRect(20, 380, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.rfwifi_modulationsend_cmd = QtWidgets.QPushButton(self.rfwifi_frame)
        self.rfwifi_modulationsend_cmd.setGeometry(QtCore.QRect(20, 210, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_modulationsend_cmd.setFont(font)
        self.rfwifi_modulationsend_cmd.setObjectName("rfwifi_modulationsend_cmd")
        self.rfwifi_tonesend_cmd = QtWidgets.QPushButton(self.rfwifi_frame)
        self.rfwifi_tonesend_cmd.setGeometry(QtCore.QRect(20, 340, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_tonesend_cmd.setFont(font)
        self.rfwifi_tonesend_cmd.setObjectName("rfwifi_tonesend_cmd")
        self.rfwifi_rxsend_cmd = QtWidgets.QPushButton(self.rfwifi_frame)
        self.rfwifi_rxsend_cmd.setGeometry(QtCore.QRect(20, 440, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_rxsend_cmd.setFont(font)
        self.rfwifi_rxsend_cmd.setObjectName("rfwifi_rxsend_cmd")
        self.rfwifi_modulationstop = QtWidgets.QPushButton(self.rfwifi_frame)
        self.rfwifi_modulationstop.setGeometry(QtCore.QRect(270, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_modulationstop.setFont(font)
        self.rfwifi_modulationstop.setObjectName("rfwifi_modulationstop")
        self.rfwifi_rxstop = QtWidgets.QPushButton(self.rfwifi_frame)
        self.rfwifi_rxstop.setGeometry(QtCore.QRect(170, 480, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfwifi_rxstop.setFont(font)
        self.rfwifi_rxstop.setObjectName("rfwifi_rxstop")
        self.cmdinput = QtWidgets.QTextEdit(Form)
        self.cmdinput.setGeometry(QtCore.QRect(640, 10, 351, 171))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.cmdinput.setFont(font)
        self.cmdinput.setObjectName("cmdinput")
        self.sendcmd_btn = QtWidgets.QPushButton(Form)
        self.sendcmd_btn.setGeometry(QtCore.QRect(640, 190, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.sendcmd_btn.setFont(font)
        self.sendcmd_btn.setObjectName("sendcmd_btn")
        self.stop_btn = QtWidgets.QPushButton(Form)
        self.stop_btn.setGeometry(QtCore.QRect(770, 190, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.cmdoutput = QtWidgets.QTextEdit(Form)
        self.cmdoutput.setGeometry(QtCore.QRect(640, 270, 351, 261))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.cmdoutput.setFont(font)
        self.cmdoutput.setObjectName("cmdoutput")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(640, 240, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.rfbt_frame = QtWidgets.QFrame(Form)
        self.rfbt_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt_frame.setFont(font)
        self.rfbt_frame.setAutoFillBackground(True)
        self.rfbt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfbt_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rfbt_frame.setObjectName("rfbt_frame")
        self.label_30 = QtWidgets.QLabel(self.rfbt_frame)
        self.label_30.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.rfbt_frame)
        self.label_31.setGeometry(QtCore.QRect(20, 110, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_35 = QtWidgets.QLabel(self.rfbt_frame)
        self.label_35.setGeometry(QtCore.QRect(120, 140, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.rfbt_txchannel = QtWidgets.QLineEdit(self.rfbt_frame)
        self.rfbt_txchannel.setGeometry(QtCore.QRect(20, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt_txchannel.setFont(font)
        self.rfbt_txchannel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfbt_txchannel.setObjectName("rfbt_txchannel")
        self.rfbt_txsend = QtWidgets.QPushButton(self.rfbt_frame)
        self.rfbt_txsend.setGeometry(QtCore.QRect(190, 170, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt_txsend.setFont(font)
        self.rfbt_txsend.setObjectName("rfbt_txsend")
        self.rfbt_rxchannel = QtWidgets.QLineEdit(self.rfbt_frame)
        self.rfbt_rxchannel.setGeometry(QtCore.QRect(20, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt_rxchannel.setFont(font)
        self.rfbt_rxchannel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfbt_rxchannel.setObjectName("rfbt_rxchannel")
        self.rfbt_rxsend = QtWidgets.QPushButton(self.rfbt_frame)
        self.rfbt_rxsend.setGeometry(QtCore.QRect(190, 280, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt_rxsend.setFont(font)
        self.rfbt_rxsend.setObjectName("rfbt_rxsend")
        self.label_37 = QtWidgets.QLabel(self.rfbt_frame)
        self.label_37.setGeometry(QtCore.QRect(20, 220, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.rfbt_frame)
        self.label_38.setGeometry(QtCore.QRect(120, 250, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.rfbt_enable = QtWidgets.QPushButton(self.rfbt_frame)
        self.rfbt_enable.setGeometry(QtCore.QRect(20, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt_enable.setFont(font)
        self.rfbt_enable.setObjectName("rfbt_enable")
        self.rfbt_disable = QtWidgets.QPushButton(self.rfbt_frame)
        self.rfbt_disable.setGeometry(QtCore.QRect(190, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt_disable.setFont(font)
        self.rfbt_disable.setObjectName("rfbt_disable")
        self.rfbt_txcmd = QtWidgets.QPushButton(self.rfbt_frame)
        self.rfbt_txcmd.setGeometry(QtCore.QRect(20, 170, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt_txcmd.setFont(font)
        self.rfbt_txcmd.setObjectName("rfbt_txcmd")
        self.rfbt_rxcmd = QtWidgets.QPushButton(self.rfbt_frame)
        self.rfbt_rxcmd.setGeometry(QtCore.QRect(20, 280, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfbt_rxcmd.setFont(font)
        self.rfbt_rxcmd.setObjectName("rfbt_rxcmd")
        self.rf900_frame = QtWidgets.QFrame(Form)
        self.rf900_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rf900_frame.setFont(font)
        self.rf900_frame.setAutoFillBackground(True)
        self.rf900_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rf900_frame.setObjectName("rf900_frame")
        self.label_32 = QtWidgets.QLabel(self.rf900_frame)
        self.label_32.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.rf900_frame)
        self.label_33.setGeometry(QtCore.QRect(20, 60, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_36 = QtWidgets.QLabel(self.rf900_frame)
        self.label_36.setGeometry(QtCore.QRect(120, 90, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.rf900_txchannel = QtWidgets.QLineEdit(self.rf900_frame)
        self.rf900_txchannel.setGeometry(QtCore.QRect(20, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rf900_txchannel.setFont(font)
        self.rf900_txchannel.setAlignment(QtCore.Qt.AlignCenter)
        self.rf900_txchannel.setObjectName("rf900_txchannel")
        self.rf900_txsend = QtWidgets.QPushButton(self.rf900_frame)
        self.rf900_txsend.setGeometry(QtCore.QRect(20, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rf900_txsend.setFont(font)
        self.rf900_txsend.setObjectName("rf900_txsend")
        self.rf900_rxchannel = QtWidgets.QLineEdit(self.rf900_frame)
        self.rf900_rxchannel.setGeometry(QtCore.QRect(20, 220, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rf900_rxchannel.setFont(font)
        self.rf900_rxchannel.setAlignment(QtCore.Qt.AlignCenter)
        self.rf900_rxchannel.setObjectName("rf900_rxchannel")
        self.rf900_rxsend = QtWidgets.QPushButton(self.rf900_frame)
        self.rf900_rxsend.setGeometry(QtCore.QRect(20, 250, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rf900_rxsend.setFont(font)
        self.rf900_rxsend.setObjectName("rf900_rxsend")
        self.label_39 = QtWidgets.QLabel(self.rf900_frame)
        self.label_39.setGeometry(QtCore.QRect(20, 190, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.rf900_frame)
        self.label_40.setGeometry(QtCore.QRect(120, 220, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.rf900_txstop = QtWidgets.QPushButton(self.rf900_frame)
        self.rf900_txstop.setGeometry(QtCore.QRect(190, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rf900_txstop.setFont(font)
        self.rf900_txstop.setObjectName("rf900_txstop")
        self.rf900_rxcounter = QtWidgets.QPushButton(self.rf900_frame)
        self.rf900_rxcounter.setGeometry(QtCore.QRect(190, 250, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rf900_rxcounter.setFont(font)
        self.rf900_rxcounter.setObjectName("rf900_rxcounter")
        self.rf900_txtone = QtWidgets.QPushButton(self.rf900_frame)
        self.rf900_txtone.setGeometry(QtCore.QRect(20, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rf900_txtone.setFont(font)
        self.rf900_txtone.setObjectName("rf900_txtone")
        self.rfzwave_frame = QtWidgets.QFrame(Form)
        self.rfzwave_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave_frame.setFont(font)
        self.rfzwave_frame.setAutoFillBackground(True)
        self.rfzwave_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfzwave_frame.setObjectName("rfzwave_frame")
        self.label_34 = QtWidgets.QLabel(self.rfzwave_frame)
        self.label_34.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_41 = QtWidgets.QLabel(self.rfzwave_frame)
        self.label_41.setGeometry(QtCore.QRect(20, 60, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.rfzwave_txsend = QtWidgets.QPushButton(self.rfzwave_frame)
        self.rfzwave_txsend.setGeometry(QtCore.QRect(20, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave_txsend.setFont(font)
        self.rfzwave_txsend.setObjectName("rfzwave_txsend")
        self.rfzwave_rxchannel = QtWidgets.QLineEdit(self.rfzwave_frame)
        self.rfzwave_rxchannel.setGeometry(QtCore.QRect(20, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave_rxchannel.setFont(font)
        self.rfzwave_rxchannel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfzwave_rxchannel.setObjectName("rfzwave_rxchannel")
        self.rfzwave_rxsend = QtWidgets.QPushButton(self.rfzwave_frame)
        self.rfzwave_rxsend.setGeometry(QtCore.QRect(20, 210, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave_rxsend.setFont(font)
        self.rfzwave_rxsend.setObjectName("rfzwave_rxsend")
        self.label_43 = QtWidgets.QLabel(self.rfzwave_frame)
        self.label_43.setGeometry(QtCore.QRect(20, 160, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.rfzwave_frame)
        self.label_44.setGeometry(QtCore.QRect(120, 180, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.rfzwave_txchannel = QtWidgets.QLineEdit(self.rfzwave_frame)
        self.rfzwave_txchannel.setGeometry(QtCore.QRect(20, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave_txchannel.setFont(font)
        self.rfzwave_txchannel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfzwave_txchannel.setObjectName("rfzwave_txchannel")
        self.label_45 = QtWidgets.QLabel(self.rfzwave_frame)
        self.label_45.setGeometry(QtCore.QRect(120, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.rfzwave_txstop = QtWidgets.QPushButton(self.rfzwave_frame)
        self.rfzwave_txstop.setGeometry(QtCore.QRect(190, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave_txstop.setFont(font)
        self.rfzwave_txstop.setObjectName("rfzwave_txstop")
        self.rfzwave_rxcounter = QtWidgets.QPushButton(self.rfzwave_frame)
        self.rfzwave_rxcounter.setGeometry(QtCore.QRect(190, 210, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave_rxcounter.setFont(font)
        self.rfzwave_rxcounter.setObjectName("rfzwave_rxcounter")
        self.rfzwave_txtone = QtWidgets.QPushButton(self.rfzwave_frame)
        self.rfzwave_txtone.setGeometry(QtCore.QRect(190, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave_txtone.setFont(font)
        self.rfzwave_txtone.setObjectName("rfzwave_txtone")
        self.rfzwave_txpower = QtWidgets.QLineEdit(self.rfzwave_frame)
        self.rfzwave_txpower.setGeometry(QtCore.QRect(190, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rfzwave_txpower.setFont(font)
        self.rfzwave_txpower.setAlignment(QtCore.Qt.AlignCenter)
        self.rfzwave_txpower.setObjectName("rfzwave_txpower")
        self.label_73 = QtWidgets.QLabel(self.rfzwave_frame)
        self.label_73.setGeometry(QtCore.QRect(290, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_73.setFont(font)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.rflte_frame = QtWidgets.QFrame(Form)
        self.rflte_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_frame.setFont(font)
        self.rflte_frame.setAutoFillBackground(True)
        self.rflte_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rflte_frame.setObjectName("rflte_frame")
        self.label_47 = QtWidgets.QLabel(self.rflte_frame)
        self.label_47.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.rflte_txband = QtWidgets.QLineEdit(self.rflte_frame)
        self.rflte_txband.setGeometry(QtCore.QRect(20, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_txband.setFont(font)
        self.rflte_txband.setAlignment(QtCore.Qt.AlignCenter)
        self.rflte_txband.setObjectName("rflte_txband")
        self.rflte_txsend = QtWidgets.QPushButton(self.rflte_frame)
        self.rflte_txsend.setGeometry(QtCore.QRect(20, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_txsend.setFont(font)
        self.rflte_txsend.setObjectName("rflte_txsend")
        self.label_51 = QtWidgets.QLabel(self.rflte_frame)
        self.label_51.setGeometry(QtCore.QRect(20, 70, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.rflte_frame)
        self.label_52.setGeometry(QtCore.QRect(120, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.rflte_frame)
        self.label_53.setGeometry(QtCore.QRect(20, 220, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.rflte_frame)
        self.label_54.setGeometry(QtCore.QRect(120, 280, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.rflte_rxsend = QtWidgets.QPushButton(self.rflte_frame)
        self.rflte_rxsend.setGeometry(QtCore.QRect(20, 340, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_rxsend.setFont(font)
        self.rflte_rxsend.setObjectName("rflte_rxsend")
        self.rflte_rxpath = QtWidgets.QLineEdit(self.rflte_frame)
        self.rflte_rxpath.setGeometry(QtCore.QRect(20, 280, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_rxpath.setFont(font)
        self.rflte_rxpath.setAlignment(QtCore.Qt.AlignCenter)
        self.rflte_rxpath.setObjectName("rflte_rxpath")
        self.label_55 = QtWidgets.QLabel(self.rflte_frame)
        self.label_55.setGeometry(QtCore.QRect(120, 130, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.rflte_txchannel = QtWidgets.QLineEdit(self.rflte_frame)
        self.rflte_txchannel.setGeometry(QtCore.QRect(20, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_txchannel.setFont(font)
        self.rflte_txchannel.setAlignment(QtCore.Qt.AlignCenter)
        self.rflte_txchannel.setObjectName("rflte_txchannel")
        self.rflte_rxband = QtWidgets.QLineEdit(self.rflte_frame)
        self.rflte_rxband.setGeometry(QtCore.QRect(20, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_rxband.setFont(font)
        self.rflte_rxband.setAlignment(QtCore.Qt.AlignCenter)
        self.rflte_rxband.setObjectName("rflte_rxband")
        self.label_56 = QtWidgets.QLabel(self.rflte_frame)
        self.label_56.setGeometry(QtCore.QRect(120, 250, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_60 = QtWidgets.QLabel(self.rflte_frame)
        self.label_60.setGeometry(QtCore.QRect(290, 280, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.rflte_rxlna = QtWidgets.QLineEdit(self.rflte_frame)
        self.rflte_rxlna.setGeometry(QtCore.QRect(190, 280, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_rxlna.setFont(font)
        self.rflte_rxlna.setAlignment(QtCore.Qt.AlignCenter)
        self.rflte_rxlna.setObjectName("rflte_rxlna")
        self.rflte_rxchn = QtWidgets.QLineEdit(self.rflte_frame)
        self.rflte_rxchn.setGeometry(QtCore.QRect(190, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_rxchn.setFont(font)
        self.rflte_rxchn.setAlignment(QtCore.Qt.AlignCenter)
        self.rflte_rxchn.setObjectName("rflte_rxchn")
        self.label_72 = QtWidgets.QLabel(self.rflte_frame)
        self.label_72.setGeometry(QtCore.QRect(290, 250, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.label_83 = QtWidgets.QLabel(self.rflte_frame)
        self.label_83.setGeometry(QtCore.QRect(120, 310, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.rflte_bw = QtWidgets.QLineEdit(self.rflte_frame)
        self.rflte_bw.setGeometry(QtCore.QRect(20, 310, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_bw.setFont(font)
        self.rflte_bw.setAlignment(QtCore.Qt.AlignCenter)
        self.rflte_bw.setObjectName("rflte_bw")
        self.label_96 = QtWidgets.QLabel(self.rflte_frame)
        self.label_96.setGeometry(QtCore.QRect(280, 130, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_96.setFont(font)
        self.label_96.setObjectName("label_96")
        self.rflte_txgain = QtWidgets.QLineEdit(self.rflte_frame)
        self.rflte_txgain.setGeometry(QtCore.QRect(180, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_txgain.setFont(font)
        self.rflte_txgain.setAlignment(QtCore.Qt.AlignCenter)
        self.rflte_txgain.setObjectName("rflte_txgain")
        self.rflte_txenable = QtWidgets.QLineEdit(self.rflte_frame)
        self.rflte_txenable.setGeometry(QtCore.QRect(180, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_txenable.setFont(font)
        self.rflte_txenable.setAlignment(QtCore.Qt.AlignCenter)
        self.rflte_txenable.setObjectName("rflte_txenable")
        self.label_97 = QtWidgets.QLabel(self.rflte_frame)
        self.label_97.setGeometry(QtCore.QRect(280, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_97.setFont(font)
        self.label_97.setObjectName("label_97")
        self.rflte_rxstop = QtWidgets.QPushButton(self.rflte_frame)
        self.rflte_rxstop.setGeometry(QtCore.QRect(190, 340, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_rxstop.setFont(font)
        self.rflte_rxstop.setObjectName("rflte_rxstop")
        self.rflte_txstop = QtWidgets.QPushButton(self.rflte_frame)
        self.rflte_txstop.setGeometry(QtCore.QRect(190, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.rflte_txstop.setFont(font)
        self.rflte_txstop.setObjectName("rflte_txstop")
        self.label_48 = QtWidgets.QLabel(Form)
        self.label_48.setGeometry(QtCore.QRect(30, 10, 191, 21))
        self.label_48.setMinimumSize(QtCore.QSize(191, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_57 = QtWidgets.QLabel(Form)
        self.label_57.setGeometry(QtCore.QRect(20, 30, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.welcome_frame = QtWidgets.QFrame(Form)
        self.welcome_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.welcome_frame.setFont(font)
        self.welcome_frame.setAutoFillBackground(True)
        self.welcome_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.welcome_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.welcome_frame.setObjectName("welcome_frame")
        self.label_58 = QtWidgets.QLabel(self.welcome_frame)
        self.label_58.setGeometry(QtCore.QRect(0, 190, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_61 = QtWidgets.QLabel(self.welcome_frame)
        self.label_61.setGeometry(QtCore.QRect(20, 230, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.welcome_frame)
        self.label_62.setGeometry(QtCore.QRect(10, 260, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setUnderline(True)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.exittest_btn = QtWidgets.QPushButton(self.welcome_frame)
        self.exittest_btn.setGeometry(QtCore.QRect(90, 360, 201, 23))
        self.exittest_btn.setObjectName("exittest_btn")
        self.label_59 = QtWidgets.QLabel(Form)
        self.label_59.setGeometry(QtCore.QRect(20, 50, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.funcio_frame = QtWidgets.QFrame(Form)
        self.funcio_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcio_frame.setFont(font)
        self.funcio_frame.setAutoFillBackground(True)
        self.funcio_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.funcio_frame.setObjectName("funcio_frame")
        self.funcio_tx = QtWidgets.QPushButton(self.funcio_frame)
        self.funcio_tx.setGeometry(QtCore.QRect(70, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcio_tx.setFont(font)
        self.funcio_tx.setObjectName("funcio_tx")
        self.label_70 = QtWidgets.QLabel(self.funcio_frame)
        self.label_70.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.funcio_frame)
        self.label_71.setGeometry(QtCore.QRect(0, 50, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_71.setFont(font)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.funcio_txedit = QtWidgets.QLineEdit(self.funcio_frame)
        self.funcio_txedit.setGeometry(QtCore.QRect(160, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcio_txedit.setFont(font)
        self.funcio_txedit.setObjectName("funcio_txedit")
        self.funcio_rx = QtWidgets.QPushButton(self.funcio_frame)
        self.funcio_rx.setGeometry(QtCore.QRect(70, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcio_rx.setFont(font)
        self.funcio_rx.setObjectName("funcio_rx")
        self.funcio_rxedit = QtWidgets.QLineEdit(self.funcio_frame)
        self.funcio_rxedit.setGeometry(QtCore.QRect(160, 130, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funcio_rxedit.setFont(font)
        self.funcio_rxedit.setObjectName("funcio_rxedit")
        self.funclte_frame = QtWidgets.QFrame(Form)
        self.funclte_frame.setGeometry(QtCore.QRect(250, 10, 381, 521))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funclte_frame.setFont(font)
        self.funclte_frame.setAutoFillBackground(True)
        self.funclte_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.funclte_frame.setObjectName("funclte_frame")
        self.funclte_on = QtWidgets.QPushButton(self.funclte_frame)
        self.funclte_on.setGeometry(QtCore.QRect(110, 110, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funclte_on.setFont(font)
        self.funclte_on.setObjectName("funclte_on")
        self.label = QtWidgets.QLabel(self.funclte_frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.funclte_off = QtWidgets.QPushButton(self.funclte_frame)
        self.funclte_off.setGeometry(QtCore.QRect(110, 150, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funclte_off.setFont(font)
        self.funclte_off.setObjectName("funclte_off")
        self.funclte_mainset = QtWidgets.QPushButton(self.funclte_frame)
        self.funclte_mainset.setGeometry(QtCore.QRect(110, 230, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funclte_mainset.setFont(font)
        self.funclte_mainset.setObjectName("funclte_mainset")
        self.funclte_mainset_2 = QtWidgets.QPushButton(self.funclte_frame)
        self.funclte_mainset_2.setGeometry(QtCore.QRect(110, 280, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.funclte_mainset_2.setFont(font)
        self.funclte_mainset_2.setObjectName("funclte_mainset_2")
        self.sendat_btn = QtWidgets.QPushButton(Form)
        self.sendat_btn.setGeometry(QtCore.QRect(900, 190, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.sendat_btn.setFont(font)
        self.sendat_btn.setObjectName("sendat_btn")
        self.funcsensor_frame.raise_()
        self.funccamera.raise_()
        self.funcsiren.raise_()
        self.funcbat.raise_()
        self.funcio.raise_()
        self.rfmode.raise_()
        self.funcmode.raise_()
        self.cmdinput.raise_()
        self.sendcmd_btn.raise_()
        self.stop_btn.raise_()
        self.cmdoutput.raise_()
        self.label_29.raise_()
        self.label_48.raise_()
        self.label_57.raise_()
        self.label_59.raise_()
        self.funclte.raise_()
        self.funccamera_frame.raise_()
        self.funcsiren_frame.raise_()
        self.funcbat_frame.raise_()
        self.funcspk.raise_()
        self.funcwireless.raise_()
        self.funcio_frame.raise_()
        self.rf900.raise_()
        self.rfwifi.raise_()
        self.rfbt.raise_()
        self.rfzwave.raise_()
        self.rflte.raise_()
        self.rfbt_frame.raise_()
        self.rf900_frame.raise_()
        self.rfzwave_frame.raise_()
        self.funcspk_frame.raise_()
        self.funcwireless_frame.raise_()
        self.funcvoicecall.raise_()
        self.rflte_frame.raise_()
        self.sendat_btn.raise_()
        self.funclte_frame.raise_()
        self.rfwifi_frame.raise_()
        self.funcvoicecall_frame.raise_()
        self.welcome_frame.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Nortek_GC4_App"))
        self.funclte.setText(_translate("Form", " LTE"))
        self.funccamera.setText(_translate("Form", "Camera"))
        self.funcsiren.setText(_translate("Form", "SIREN/USB"))
        self.funcbat.setText(_translate("Form", "Battery mode"))
        self.funcspk.setText(_translate("Form", "Playback"))
        self.funcvoicecall.setText(_translate("Form", "Voice call"))
        self.funcwireless.setText(_translate("Form", "Wireless Setting"))
        self.funcio.setText(_translate("Form", "IO"))
        self.rfmode.setText(_translate("Form", "RF TEST Mode"))
        self.rfwifi.setText(_translate("Form", "WIFI"))
        self.rfbt.setText(_translate("Form", "Bluetooth"))
        self.rf900.setText(_translate("Form", "900Mhz"))
        self.rfzwave.setText(_translate("Form", "Z-Wave"))
        self.rflte.setText(_translate("Form", "LTE"))
        self.funcmode.setText(_translate("Form", "Function Mode"))
        self.funccamera_on.setText(_translate("Form", "Camera ON 10s"))
        self.label_2.setText(_translate("Form", "Function CAMERA"))
        self.funccamera_off.setText(_translate("Form", "Camera always ON"))
        self.funcsiren_on.setText(_translate("Form", "Siren ON"))
        self.label_3.setText(_translate("Form", "Function Siren"))
        self.funcsiren_off.setText(_translate("Form", "Siren OFF"))
        self.label_16.setText(_translate("Form", "Function USB"))
        self.funcusb_detect.setText(_translate("Form", "USB Detect"))
        self.funcbat_on.setText(_translate("Form", "Enter Battery Mode"))
        self.label_4.setText(_translate("Form", "Function Battery Mode"))
        self.funcspk_on.setText(_translate("Form", "Playback"))
        self.label_5.setText(_translate("Form", "Function Playback"))
        self.funcspk_off.setText(_translate("Form", "Stop"))
        self.funcvalue.setText(_translate("Form", "15"))
        self.funccut.setText(_translate("Form", "-"))
        self.funcadd.setText(_translate("Form", "+"))
        self.funcvoicecall_call.setText(_translate("Form", "Call out"))
        self.label_6.setText(_translate("Form", "Function Voice Call"))
        self.funcvoicecall_receive.setText(_translate("Form", "Receive Call"))
        self.funcvoicecall_hangup.setText(_translate("Form", "hangup"))
        self.readapn_btn.setText(_translate("Form", "Read APN Setting"))
        self.readip_btn.setText(_translate("Form", "Read IP Address"))
        self.readlte_btn.setText(_translate("Form", "Read presence of 4G data traffic"))
        self.ping_btn.setText(_translate("Form", "Start ping"))
        self.setapn_btn.setText(_translate("Form", "Set Manual APN"))
        self.setapn_edit.setText(_translate("Form", "3,\"IPV4V6\",\"vzwinternet\",\"0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0\",0,0,0,0"))
        self.pinginter_edit.setText(_translate("Form", "1800"))
        self.setautoapn_btn.setText(_translate("Form", "SET AUTO APN"))
        self.stopping_btn.setText(_translate("Form", "Stop ping"))
        self.label_17.setText(_translate("Form", "ping count per hour"))
        self.label_18.setText(_translate("Form", "web address"))
        self.web_edit.setText(_translate("Form", "www.alarm.com"))
        self.speedtest_btn.setText(_translate("Form", "4G data speed test"))
        self.label_7.setText(_translate("Form", "Function Wireless Setting"))
        self.label_63.setText(_translate("Form", "WIFI"))
        self.label_64.setText(_translate("Form", "SSID"))
        self.label_65.setText(_translate("Form", "Password"))
        self.funcwireless_wifion.setText(_translate("Form", "Connect"))
        self.funcwireless_wifioff.setText(_translate("Form", "Disconnect"))
        self.funcwireless_btscanon.setText(_translate("Form", "Scan on"))
        self.label_66.setText(_translate("Form", "Bluetooth"))
        self.funcwireless_btoff.setText(_translate("Form", "Disconnect"))
        self.funcwireless_btmac.setText(_translate("Form", "18:54:CF:90:8E:D5"))
        self.label_67.setText(_translate("Form", "Device MAC"))
        self.funcwireless_btscanoff.setText(_translate("Form", "Devices"))
        self.funcwireless_btpair.setText(_translate("Form", "Pair"))
        self.label_68.setText(_translate("Form", "900MHz"))
        self.funcwireless_900off.setText(_translate("Form", "Events 10s"))
        self.funcwireless_900on.setText(_translate("Form", "Pair"))
        self.label_69.setText(_translate("Form", "345MHz: Receiver Only"))
        self.funcwireless_345on.setText(_translate("Form", "Events 10s"))
        self.funcwireless_enablebt.setText(_translate("Form", "Enable Bluetooth"))
        self.funcsensor_btn.setText(_translate("Form", "Sensor"))
        self.label_8.setText(_translate("Form", "Function Sensor"))
        self.label_9.setText(_translate("Form", "RF TEST MODE WIFI"))
        self.label_10.setText(_translate("Form", "Continue Modulation Mode Tx"))
        self.label_11.setText(_translate("Form", "country"))
        self.rfwifi_region.setText(_translate("Form", "ALL"))
        self.label_12.setText(_translate("Form", "band"))
        self.label_13.setText(_translate("Form", "txbw"))
        self.label_14.setText(_translate("Form", "mode"))
        self.label_15.setText(_translate("Form", "channel"))
        self.rfwifi_band.setText(_translate("Form", "b"))
        self.rfwifi_txbw.setText(_translate("Form", "-1"))
        self.rfwifi_mode.setText(_translate("Form", "2g_rate -r 54 -b 20"))
        self.rfwifi_channel.setText(_translate("Form", "channel 11"))
        self.rfwifi_modulationsend.setText(_translate("Form", "Tx Start"))
        self.rfwifi_tonechannel.setText(_translate("Form", "1"))
        self.rfwifi_tonesend.setText(_translate("Form", "Single Tone Tx Send"))
        self.label_23.setText(_translate("Form", "Continue Single Tone Tx"))
        self.label_24.setText(_translate("Form", "Channel"))
        self.rfwifi_tonefrequency.setText(_translate("Form", "b"))
        self.label_25.setText(_translate("Form", "Frequnecy Band b or a (b=2.4G, a=5G)"))
        self.label_26.setText(_translate("Form", "Channel"))
        self.rfwifi_rxchannel.setText(_translate("Form", "chanspec 36/40"))
        self.rfwifi_rxsend.setText(_translate("Form", "Rx Send"))
        self.label_28.setText(_translate("Form", "Continue Rx"))
        self.rfwifi_modulationsend_cmd.setText(_translate("Form", "Check CMD"))
        self.rfwifi_tonesend_cmd.setText(_translate("Form", "Check CMD"))
        self.rfwifi_rxsend_cmd.setText(_translate("Form", "Check CMD"))
        self.rfwifi_modulationstop.setText(_translate("Form", "Tx stop"))
        self.rfwifi_rxstop.setText(_translate("Form", "Rx Stop"))
        self.sendcmd_btn.setText(_translate("Form", "Send"))
        self.stop_btn.setText(_translate("Form", "Clean"))
        self.label_29.setText(_translate("Form", "LOG OUTPUT"))
        self.label_30.setText(_translate("Form", "RF TEST MODE BLUETOOTH"))
        self.label_31.setText(_translate("Form", "Continue Modulation Mode Tx"))
        self.label_35.setText(_translate("Form", "Channel"))
        self.rfbt_txchannel.setText(_translate("Form", "13"))
        self.rfbt_txsend.setText(_translate("Form", "Modulation Tx Send"))
        self.rfbt_rxchannel.setText(_translate("Form", "13"))
        self.rfbt_rxsend.setText(_translate("Form", "Rx Send"))
        self.label_37.setText(_translate("Form", "Continue Modulation mode Rx"))
        self.label_38.setText(_translate("Form", "Channel"))
        self.rfbt_enable.setText(_translate("Form", "Enable"))
        self.rfbt_disable.setText(_translate("Form", "Disable"))
        self.rfbt_txcmd.setText(_translate("Form", "Check CMD"))
        self.rfbt_rxcmd.setText(_translate("Form", "Check CMD"))
        self.label_32.setText(_translate("Form", "RF TEST MODE 900MHz"))
        self.label_33.setText(_translate("Form", "Continue Modulation Mode Tx"))
        self.label_36.setText(_translate("Form", "Channel"))
        self.rf900_txchannel.setText(_translate("Form", "1"))
        self.rf900_txsend.setText(_translate("Form", "Tx Start"))
        self.rf900_rxchannel.setText(_translate("Form", "1"))
        self.rf900_rxsend.setText(_translate("Form", "Rx Send"))
        self.label_39.setText(_translate("Form", "Continue Modulation mode Rx"))
        self.label_40.setText(_translate("Form", "Channel"))
        self.rf900_txstop.setText(_translate("Form", "Tx Stop"))
        self.rf900_rxcounter.setText(_translate("Form", "Rx counter"))
        self.rf900_txtone.setText(_translate("Form", "Tone Tx Start"))
        self.label_34.setText(_translate("Form", "RF TEST MODE Z-WAVE"))
        self.label_41.setText(_translate("Form", "Continue Modulation Mode Tx"))
        self.rfzwave_txsend.setText(_translate("Form", "Tx Start"))
        self.rfzwave_rxchannel.setText(_translate("Form", "0"))
        self.rfzwave_rxsend.setText(_translate("Form", "Rx Start"))
        self.label_43.setText(_translate("Form", "Continue Modulation mode Rx"))
        self.label_44.setText(_translate("Form", "Channel"))
        self.rfzwave_txchannel.setText(_translate("Form", "0"))
        self.label_45.setText(_translate("Form", "Channel"))
        self.rfzwave_txstop.setText(_translate("Form", " Tx Stop"))
        self.rfzwave_rxcounter.setText(_translate("Form", "Rx Counter"))
        self.rfzwave_txtone.setText(_translate("Form", "Tone Tx Start"))
        self.rfzwave_txpower.setText(_translate("Form", "25"))
        self.label_73.setText(_translate("Form", "setpower"))
        self.label_47.setText(_translate("Form", "RF TEST MODE LTE"))
        self.rflte_txband.setText(_translate("Form", "LTE BAND4"))
        self.rflte_txsend.setText(_translate("Form", "Tx Send"))
        self.label_51.setText(_translate("Form", "Continue Modulation mode Tx"))
        self.label_52.setText(_translate("Form", "LTE Band"))
        self.label_53.setText(_translate("Form", "Continue Modulation mode Rx"))
        self.label_54.setText(_translate("Form", "path"))
        self.rflte_rxsend.setText(_translate("Form", "Rx Send"))
        self.rflte_rxpath.setText(_translate("Form", "0"))
        self.label_55.setText(_translate("Form", "Channel"))
        self.rflte_txchannel.setText(_translate("Form", "20000"))
        self.rflte_rxband.setText(_translate("Form", "2"))
        self.label_56.setText(_translate("Form", "LTE Band"))
        self.label_60.setText(_translate("Form", "LNA"))
        self.rflte_rxlna.setText(_translate("Form", "0"))
        self.rflte_rxchn.setText(_translate("Form", "600"))
        self.label_72.setText(_translate("Form", "channel"))
        self.label_83.setText(_translate("Form", "BW"))
        self.rflte_bw.setText(_translate("Form", "3"))
        self.label_96.setText(_translate("Form", "tx_gain"))
        self.rflte_txgain.setText(_translate("Form", "50"))
        self.rflte_txenable.setText(_translate("Form", "ON"))
        self.label_97.setText(_translate("Form", "tx_enable"))
        self.rflte_rxstop.setText(_translate("Form", "Rx Stop"))
        self.rflte_txstop.setText(_translate("Form", "Tx Stop"))
        self.label_48.setText(_translate("Form", "Product Name: Edge_Panel"))
        self.label_57.setText(_translate("Form", "Model No: 2GIG-EDG-NA"))
        self.label_58.setText(_translate("Form", "WELCOME"))
        self.label_61.setText(_translate("Form", "1. Select Function Mode or RF TEST mode"))
        self.label_62.setText(_translate("Form", "2. Perform actions under specify mode"))
        self.exittest_btn.setText(_translate("Form", "Exit Test Mode"))
        self.label_59.setText(_translate("Form", "FVIN: 0"))
        self.funcio_tx.setText(_translate("Form", "Send TX"))
        self.label_70.setText(_translate("Form", "Function IO"))
        self.label_71.setText(_translate("Form", "Short TX and RX on the Hardware IO"))
        self.funcio_rx.setText(_translate("Form", "Get RX"))
        self.funclte_on.setText(_translate("Form", "Turn on LTE"))
        self.label.setText(_translate("Form", "Function LTE"))
        self.funclte_off.setText(_translate("Form", "Turn off LTE"))
        self.funclte_mainset.setText(_translate("Form", "Turn off  Main Set"))
        self.funclte_mainset_2.setText(_translate("Form", "Turn on Main Set"))
        self.sendat_btn.setText(_translate("Form", "SEND AT"))

